---
language: ruby
rvm:
  - 2.7.0
  - 2.6.4
  - 2.5.6
  - 2.4.7
  - 2.3.8
  - 2.2.10
  - 2.1.10
  - 2.0.0
  - jruby-9.2.8.0
  - jruby-9.1.17.0
  - 1.9.3
  - ruby-head
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.8.7
    - rvm: ree
  fast_finish: true
gemfile:
  - Gemfile
before_script:
  - rake travis:before -t
script: rake travis
after_script:
  - rake travis:after -t
notifications:
  email:
    recipients:
      - austin@rubyforge.org
    on_success: change
    on_failure: always
sudo: false
