version: '{build}'
skip_tags: true
clone_depth: 10
init: []
environment:
  matrix:
  - ruby_version: 21
  - ruby_version: 21-x64
  - ruby_version: 22
  - ruby_version: 22-x64
  - ruby_version: 23
  - ruby_version: 23-x64
  - ruby_version: 24
  - ruby_version: 24-x64
  - ruby_version: 25
  - ruby_version: 25-x64
  - ruby_version: 26
  - ruby_version: 26-x64
  - ruby_version: 27
  - ruby_version: 27-x64
install:
- SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
- ruby --version
- gem --version
- gem install bundler -v 1.17.3 --quiet --no-document
- bundler --version
- bundle install
build: off
test_script:
- rake test
